version: "1.0"
info:
  model: int-scaffold
packages:
- name: Emea02UserSuperIPaaS01Project
  gitServerName: emea02user_avivsimds_public_github
  gitUrl: https://github.com/AvivSimDS/Emea02UserSuperIPaaS01Project
  gitUsername: AvivSimDS
  gitBranch: main
